OnlineFertilizerWeb/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFertilizerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Comments = new HashSet<Comment>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public int CategoryID { get; set; }
        public int Quantity { get; set; }
        public bool Status { get; set; }
        public string Image { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}

OnlineFertilizerWeb/Controllers/CommentController.cs
using OnlineFertilizerWeb.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineFertilizerWeb.Controllers
{
    public class CommentController : Controller
    {
        private FertilizerDBEntities db = new FertilizerDBEntities();
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public ActionResult PostComment(Comment comment)
        {
            Account user = (Account)Session["USER"];

            if (ModelState.IsValid)
            {
                db.Configuration.AutoDetectChangesEnabled = false;
                comment.CreateDate = DateTime.Now;
                comment.CustomerEmail = user.Email;
                comment.Status = true;
                db.Comments.Add(comment);
                db.SaveChanges();
            }

            Product product = db.Products.Find(comment.ProductID);
            if (product == null)
            {
                return HttpNotFound();
            }
            //List<Comment> comments = db.Comments.Include(c => c.Account).Where(c => c.ProductID == id).ToList();

            List<Comment> comments = db.Comments.Include(c=>c.Account).Where(c => c.ProductID == comment.ProductID).ToList();
            ViewBag.Product = product;
            ViewBag.Comments = comments;
            return View("~/Views/Products/Details.cshtml"); // Chuyển lại về trang detail
        }
    }
}

OnlineFertilizerWeb/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineFertilizerWeb.Models;

namespace OnlineFertilizerWeb.Controllers
{
    public class ProductsController : Controller
    {
        private FertilizerDBEntities db = new FertilizerDBEntities();
        private readonly int PAGE_SIZE = 8;
        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category).Where(p => p.Status == true);
            var categories = db.Categories;
            ViewBag.categories = categories;
            ViewBag.NumberPage = Math.Ceiling((products.ToList().Count() * 1.0 / PAGE_SIZE));
            int pageIndex = 1;
            ViewBag.PageIndex = pageIndex;
            return View(products.ToList().GetRange(0, PAGE_SIZE));
        }
        // GET: Products/Search/ các parameters
        public ActionResult Search(Search search)
        {
            if (search.TxtSearch == null)
            {
                search.TxtSearch = "";
            }
            var products = db.Products.Include(p => p.Category).Where(p => p.Status == true && p.Title.ToLower().Contains(search.TxtSearch.ToLower()));
            if (search.CategoryID != 0)
            {
                products = db.Products.Include(p => p.Category).Where(p => (p.Status == true && p.CategoryID == search.CategoryID) && p.Title.ToLower().Contains(search.TxtSearch.ToLower()));
            }
            if (string.IsNullOrEmpty(search.TxtSearch))
            {
                products = db.Products.Include(p => p.Category).Where(p => p.Status == true);
                if (search.CategoryID != 0)
                {
                    products = db.Products.Include(p => p.Category).Where(p => (p.Status == true && p.CategoryID == search.CategoryID));
                }
            }
            var categories = db.Categories;
            ViewBag.categories = categories;
            ViewBag.selectCategory = search.CategoryID;
            ViewBag.txtSearch = search.TxtSearch;
            ViewBag.NumberPage = Math.Ceiling((products.ToList().Count() * 1.0 / PAGE_SIZE));
            if (search.PageIndex <=0)
            {
                search.PageIndex = 1;
            }
            ViewBag.PageIndex = search.PageIndex;
            int minIndex = (search.PageIndex - 1) * PAGE_SIZE;
            int maxIndex = Math.Min(search.PageIndex * PAGE_SIZE, products.ToList().Count);
            
            return View("~/Views/Products/Index.cshtml", products.ToList().GetRange(minIndex,maxIndex-minIndex));
        }

       

        // GET: Products/Details/{int}
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
           
            List<Comment> comments = db.Comments.Include(c=>c.Account).Where(c => c.ProductID == id).ToList();
            ViewBag.Product = product;
            ViewBag.Comments = comments;
            return View();
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineFertilizerWeb/Views/Products/Details.cshtml
@model OnlineFertilizerWeb.Models.Comment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_CommomLayout.cshtml";
}

<div class="hero-wrap hero-bread" style="background-image: url('/Content/images/bg_1.jpg');">
    <div class="container">

        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9  text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span class="mr-2"><a href="index.html">Product</a></span> <span>Product Single</span></p>
                <h1 class="mb-0 bread">Product Single</h1>
            </div>
        </div>
    </div>
</div>

<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mb-5">
                @{
                    int index = ViewBag.Product.Image.LastIndexOf("\\") + 1;
                    var realPathImage = ViewBag.Product.Image.Substring(index);
                }
                <a href="" class="image-popup"><img src="~/Content/images/@realPathImage" class="img-fluid" alt="@ViewBag.Product.Title"></a>
            </div>
            <div class="col-lg-6 product-details pl-md-5">
                <h3>@ViewBag.Product.Title</h3>
                <div class="rating d-flex">
                    <p class="text-left mr-4">
                        <a href="#" class="mr-2">5.0</a>
                        <a href="#"><span class="ion-ios-star-outline"></span></a>
                        <a href="#"><span class="ion-ios-star-outline"></span></a>
                        <a href="#"><span class="ion-ios-star-outline"></span></a>
                        <a href="#"><span class="ion-ios-star-outline"></span></a>
                        <a href="#"><span class="ion-ios-star-outline"></span></a>
                    </p>
                    <p class="text-left mr-4">
                        <a href="#" class="mr-2" style="color: #000;">100 <span style="color: #bbb;">Rating</span></a>
                    </p>
                    <p class="text-left">
                        <a href="#" class="mr-2" style="color: #000;">500 <span style="color: #bbb;">Sold</span></a>
                    </p>
                </div>
                <p class="price"><span>@ViewBag.Product.Price VND</span></p>
                <p>
                    @ViewBag.Product.Description
                </p>
                @using (Html.BeginForm("AddToCart", "Cart", FormMethod.Post))
                {
                    <div class="row mt-4">
                        <div class="w-100"></div>
                        <div class="input-group col-md-6 d-flex mb-3">
                            <span class="input-group-btn mr-2">
                                <button type="button" class="quantity-left-minus btn" data-type="minus" data-field="">
                                    <i class="ion-ios-remove"></i>
                                </button>
                            </span>
                            <input type="text" id="quantity" name="quantity" class="form-control input-number" value="1" min="1" max="100">
                            <span class="input-group-btn ml-2">
                                <button type="button" class="quantity-right-plus btn" data-type="plus" data-field="">
                                    <i class="ion-ios-add"></i>
                                </button>
                            </span>
                        </div>
                        <div class="w-100"></div>
                        
                    </div>
                    <input type="hidden" name="ID" value="@ViewBag.Product.ID" />
                    //   @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" value="Add To cart" class="btn btn-black py-3 px-5" />
                }

            </div>
        </div>
    </div>
</section>

<div class="container">
    @using (Html.BeginForm("PostComment", "Comment", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label for="comment">Your Comment</label>
            @Html.TextAreaFor(c => c.Message, new { @class = "form-control", @rows = "3" })
            @Html.ValidationMessageFor(c => c.Message, "", new { @class = "badge badge-danger" })
            <span class="badge badge-danger">@ViewBag.error</span>
        </div>
        <input type="hidden" name="ProductID" value="@ViewBag.Product.ID" />
        <div>
            <button type="submit" class="btn btn-primary justify-content-end">Send</button>
        </div>
    }
    <div class="card card-comments mb-3 wow fadeIn">
        <div class="card-header font-weight-bold">@ViewBag.Comments.Count comments</div>
        @if (ViewBag.Comments.Count > 0)
        {
            foreach (var comment in ViewBag.Comments)
            {
                <div class="card-body">
                    <div class="media d-block d-md-flex mt-4">
                        <img class="d-flex mb-3 mx-auto " src="~/Content/images/img_avatar.png" width="200px" height="auto" alt="Generic placeholder image">
                        <div class="media-body text-center text-md-left ml-md-3 ml-0">
                            <h5 class="mt-0 font-weight-bold">
                                @(comment.Account.Name)
                                <a href="" class="pull-right">
                                    <i class="fa fa-reply"></i>
                                </a>
                            </h5>
                            <h6 style="font-style:italic">Post on @comment.CreateDate</h6>
                            @(comment.Message)
                        </div>
                    </div>
                </div>
            }
        }

    </div>

    <!--/.Comments-->


</div>

OnlineFertilizerWeb/Views/Products/Index.cshtml
@model IEnumerable<OnlineFertilizerWeb.Models.Product>

@{
    ViewBag.Title = "Product";
    Layout = "~/Views/Shared/_CommomLayout.cshtml";
}


<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 mb-5 text-center">
                <ul class="product-category">
                    @{
                        var searchValue = ViewBag.txtSearch;
                        if (string.IsNullOrEmpty(searchValue))
                        {
                            searchValue = "";
                        }
                    }
                    <li><a id="category_0" href="@Url.Action("Search","Products", new {  CategoryID=0, PageIndex=1 })">Tất cả</a></li>
                    @foreach (var category in ViewBag.categories)
                    {
                        <li><a id="category_@category.ID" href="@Url.Action("Search","Products", new { CategoryID=category.ID, txtSearch=searchValue, PageIndex=1 })">@category.Name</a></li>
                    }

                </ul>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-8 mb-5">
                <form action="@Url.Action("Search", "Products")">
                    <div class="input-group  text-center">
                        <input type="hidden" name="categoryID" value="@ViewBag.selectCategory" />
                        <input type="text" class="form-control" placeholder="Search this product" name="txtSearch" value="@searchValue">
                        <div class="input-group-append">
                            <button class="btn btn-secondary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        @if (Model.Count() == 0)
        {
            <h1 class="text-center text-danger">Products are not found!</h1>
        }
        <div class="row">
            @foreach (var item in Model)
            {

                <div class="col-md-6 col-lg-3 ">

                    <div class="product">
                        <a href="@Url.Action("Details", "Products", new { id = item.ID })" class="img-prod">
                            @{
                                int index = item.Image.LastIndexOf("\\") + 1;
                                var realPathImage = item.Image.Substring(index);
                            }
                            <img class="img-fluid" src="~/Content/images/@realPathImage " alt="@Html.DisplayFor(modelItem=>item.Title)" />
                            <span class="status">30%</span>
                            <div class="overlay"></div>
                        </a>
                        <div class="text py-3 pb-4 px-3 text-center">
                            <h3><a href="#">@item.Title</a></h3>
                            <div class="d-flex">
                                <div class="pricing">
                                    <p class="price"><span class="mr-2 price-dc">@(item.Price + 30) VND</span><span class="price-sale">@item.Price VND</span></p>
                                </div>
                            </div>
                            <div class="bottom-area d-flex px-3">
                                <div class="m-auto d-flex">
                                    <a href="#" class="add-to-cart d-flex justify-content-center align-items-center text-center">
                                        <span><i class="ion-ios-menu"></i></span>
                                    </a>
                                    <a href="@Url.Action("AddToCart","Cart", new { id = item.ID, quantity=1 })" class="buy-now d-flex justify-content-center align-items-center mx-1">
                                        <span><i class="ion-ios-cart"></i></span>
                                    </a>
                                    <a href="#" class="heart d-flex justify-content-center align-items-center ">
                                        <span><i class="ion-ios-heart"></i></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>

                        @for (int i = 1; i <= ViewBag.NumberPage; i++)
                        {
                            if (ViewBag.PageIndex == i)
                            {
                                <li class="active"><a href="@Url.Action("Search","Products", new { CategoryID=ViewBag.selectCategory, txtSearch=searchValue, PageIndex=i })">@i</a></li>
                            }
                            if (ViewBag.PageIndex != i)
                            {
                                <li class=""><a href="@Url.Action("Search","Products", new { CategoryID=ViewBag.selectCategory, txtSearch=searchValue, PageIndex=i })">@i</a></li>
                            }

                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>